version: '3'
services:
  example:
    container_name: example
    build:
      dockerfile: ./Dockerfile
    ports:
      - "0.0.0.0:10000:8888"
    env_file: .env.prod
    restart: unless-stopped
    command: ["./scripts/start.sh"]
