version: '3'
services:
  example:
    container_name: example
    build:
      dockerfile: ./Dockerfile
    ports:
      - "127.0.0.1:10000:8888"
    env_file: .env.dev
    restart: unless-stopped
    command: ["./scripts/start.sh"]
